#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

url=$1
shift

export EMOJI_PICKER_URL="$url"

rofi \
    --show-icons \
    "$@" \
    -show Emojis -modes "Emojis:$SCRIPT_DIR/picker"

